### ISSUE TITLE
Invalid Params error

### ISSUE THREAD

**Issue by sean-trace** [philliphoff/carwings2#19]
I am getting the following error when running the sample getLiveStatus.js

```
{"status":404,"message":"INVALID PARAMS"}
Response did not include vehicle information.
Response did not include a customer info object.
Error: Login failed
    at C:\Users\sean.trace\Documents\nissan\node_modules\carwings2\release\Client.js:26:37
    at Request._callback (C:\Users\sean.trace\Documents\nissan\node_modules\carwings2\release\Api.js:53:13)
    at Request.self.callback (C:\Users\sean.trace\Documents\nissan\node_modules\request\request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (C:\Users\sean.trace\Documents\nissan\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (C:\Users\sean.trace\Documents\nissan\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
```

The python version is working still.

**Comment by sean-trace** [comment]
Had wrong regionCode :-(

**Comment by philliphoff** [comment]
Glad you got it resolved!  That said, it wouldn't have been the first time that the response schema had been subtly changed without warning.  Let me know if you run into any other issues.
