### ISSUE TITLE
Can't use it.

### ISSUE THREAD

**Issue by fab33** [philliphoff/carwings2#8]
`npm install carwings2 --save
npm WARN saveError ENOENT: no such file or directory, open '/tmp/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.
`
And when I start a a script : 
`node /tmp/leaf.js
module.js:327
    throw err;
    ^

Error: Cannot find module 'carwings2'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/tmp/leaf.js:1:78)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
`

**Comment by philliphoff** [comment]
It looks like there was no existing `package.json` when you tried to install `carwings2`.  Maybe do a `npm init` and try again?

**Comment by fab33** [comment]
After a long time it doesn't work ...
I made npm init, npm --save carwings2
npm list seems to be ok but I have always this error 
Error: Cannot find module 'carwings2'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/furax/LEAF-info/test.js:4:16)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)

**Comment by fab33** [comment]
Precision : I try with global install (npm -g) And i see module in /usr/lib/node_modules/carwings2/ and NODE_PATH is ok /usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript but The sample on first page always complain about carwings2 ...

**Comment by fab33** [comment]
Finnaly I find why ! In you package.json, main is a reference to release/index.js and filenmae is Index.js (Maj 'i').
So now the script run but return a 404 error even I change region code (pycarwings2 works ...)

**Comment by jlilja** [comment]
Had the same problem with the capitalized i - Thanks @fab33 for the follow up. 

This should be an easy fix - @philliphoff are you up for a fix or do you want a PR?

**Comment by philliphoff** [comment]
I've updated the package (both for the capitalization issue as well as updating the endpoint API).  Unfortunately, as I sold my beloved Leaf (too small for my growing family), I'm flying a bit blind as I no longer have an active Carwings account (or car) with which to test.

**Comment by philliphoff** [comment]
See if version 2 resolves your issues.  If it doesn't, please submit a (hopefully better tested) PR and I'll merge it in.
